import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import InputForm from "../components/InputForm";
import UserTable from "../components/UserTable";
import { UserInfo } from "../interfaces/user.interfaces";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const [users, setUsers] = useState<UserInfo[]>([]);
  const [input, setInput] = useState<UserInfo>({
    firstName: "",
    lastName: "",
    phone: "",
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Challenge-1</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <InputForm input={input} setInput={setInput} setUsers={setUsers} />
      <UserTable users={users} />
    </div>
  );
};

export default Home;
