import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import InputForm from "../components/InputForm";
import UserTable from "../components/UserTable";
import { UserInfo, UserInfoBase } from "../interfaces/user.interfaces";
import styles from "../styles/Home.module.scss";
const emptyState: UserInfoBase = {
  firstName: "",
  lastName: "",
  phone: "",
};
const Home: NextPage = () => {
  const [users, setUsers] = useState<UserInfo[]>([]);
  const [input, setInput] = useState<UserInfo>({ id: "", ...emptyState });
  const [errors, setErrors] = useState<UserInfoBase>(emptyState);
  const [editingId, setEditingId] = useState<null | string>(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Challenge-1</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <InputForm
        input={input}
        setInput={setInput}
        users={users}
        setUsers={setUsers}
        errors={errors}
        setErrors={setErrors}
        editingId={editingId}
        setEditingId={setEditingId}
      />
      <UserTable
        users={users}
        setInput={setInput}
        setEditingId={setEditingId}
        setErrors={setErrors}
        emptyState={emptyState}
        setUsers={setUsers}
      />
    </div>
  );
};

export default Home;
