import type { NextPage } from "next";
import Head from "next/head";
import Widget from "../components/Widget";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Week widget</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Widget />
    </div>
  );
};

export default Home;
